### ISSUE TITLE
scp pull模式显示

### ISSUE THREAD

**Issue by PuppetA17** [iamlongalong/sshw#1]
使用scp的时候未显示用户，同时pull模式的时候没有跟路径会报错，建议pull模式下未指定路径可以下载到当前路径，不要报错
![image](https://user-images.githubusercontent.com/56722758/200484500-63d4f5d8-f1d8-43ec-9427-247ecc802475.png)

**Comment by iamlongalong** [comment]
好的，感谢提出问题。 用户名的问题会尽快修复。未指定路径之前确实被认为是命令输入错误，scp 命令本身也是如此，不过站在用户使用的角度，这个操作逻辑也好理解，接受这个提议，会在下个版本增加~

**Comment by iamlongalong** [comment]
该问题在 v1.1.2 中已解决，感谢建议~
可以通过 https://github.com/iamlongalong/sshw/releases/tag/v1.1.2 进行更新下载
